Move two-layer shallow water equations from Trixi.jl
trixi-framework/TrixiShallowWater.jl pull request #28
Opened 2024-03-11 07:22 UTC by patrickersing

This PR adds the 1D and 2D version of the `ShallowWaterEquationsTwoLayer`, that were removed from `Trixi.jl` in https://github.com/trixi-framework/Trixi.jl/pull/1809

2024-03-11 09:22 UTC, patrickersing commented
This is basically a direct copy from the files in `Trixi.jl` and I only had to qualify some of the functions.
I slightly restructured the testsets, which causes most of the deleted lines in this PR.

2024-03-12 19:12 UTC, andrewwinters5000 requested changes
Just a couple questions, but overall this already looks good! It is nice how simple it was to load in a new set of equations.

2024-03-13 07:04 UTC, patrickersing commented on src/equations/shallow_water_two_layer_1d.jl
> +    r::RealT         # ratio of rho_upper / rho_lower
Yes, for now I wanted to just move the existing Trixi.jl  functionalities.
The additional wet/dry treatment and shock capturing for the two-layer equations will then be added in an extra PR.

2024-03-13 07:08 UTC, patrickersing commented on src/equations/equations.jl
> +
Yes, we definitely should do that once we add some more equations.  I was already thinking about this when I added the equation files, but felt it was a bit superfluous to add additional comments for just these two equations.

2024-03-13 08:27 UTC, andrewwinters5000 commented on src/equations/equations.jl
> +
I agree that it is a bit of overkill now, but we can keep this in mind for the future.

2024-03-13 08:28 UTC, andrewwinters5000 approved these changes
LGTM!

2024-03-13 09:45 UTC, merged