WIP: Well-balanced mortars
trixi-framework/TrixiShallowWater.jl pull request #45
Opened 2024-05-14 07:22 UTC by andrewwinters5000

This seeks to rewrite the mortar projection routines specifically for the shallow water equations to preserve well-balancedness with non-conforming approximations. That is, the shallow water solver could utilize the AMR capabilities of `TreeMesh` or `P4estMesh`. The implementation might become delicate at wet/dry transition regions as one needs to take care in what solution values and/or fluxes are projected to and from the mortar while maintaining positivity.

2024-05-22 21:03 UTC, andrewwinters5000 commented
The current version provides a well-balanced approximation for a fully wet configuration. The `examples/p4est_2d_dgsem/elixir_shallowwater_well_balanced:wet:dry.jl` crashes in the first time step. So this requires further investigation. The main issues with the fully wet version are (1) There are still significant allocations in the computation of the mortar fluxes and (more pressing) is (2) we require a slight modification to the `P4estMortarContainer` within `Trixi.jl` to add additional storage of the unprojected large element solution in order to have this information available to subtract off a superfluous contribution of the local physical flux in the large element. I want to avoid this because this specailized mortar treatment should only need to live within the new package.

This modification is slight, but incredibly hacky. I added a third "slot" to store the large element information that I needed as given in the code snippet below. There is probably a better way to precompute and store the parent flux contributions on each mortar. I am just not familiar enough with the `P4estMesh` implementations and its various caches to see where one could store such information.
```julia
# Create mortar container and initialize mortar data.
function init_mortars(mesh::Union{P4estMesh, T8codeMesh}, equations, basis, elements)
    NDIMS = ndims(elements)
    uEltype = eltype(elements)

    # Initialize container
    n_mortars = count_required_surfaces(mesh).mortars

    _u = Vector{uEltype}(undef,
                         3 * nvariables(equations) * 2^(NDIMS - 1) *
                         nnodes(basis)^(NDIMS - 1) * n_mortars)
    u = unsafe_wrap(Array, pointer(_u),
                    (3, nvariables(equations), 2^(NDIMS - 1),
                     ntuple(_ -> nnodes(basis), NDIMS - 1)..., n_mortars))

    _neighbor_ids = Vector{Int}(undef, (2^(NDIMS - 1) + 1) * n_mortars)
    neighbor_ids = unsafe_wrap(Array, pointer(_neighbor_ids),
                               (2^(NDIMS - 1) + 1, n_mortars))

    _node_indices = Vector{NTuple{NDIMS, Symbol}}(undef, 2 * n_mortars)
    node_indices = unsafe_wrap(Array, pointer(_node_indices), (2, n_mortars))

    mortars = P4estMortarContainer{NDIMS, uEltype, NDIMS + 1, NDIMS + 3}(u,
                                                                         neighbor_ids,
                                                                         node_indices,
                                                                         _u,
                                                                         _neighbor_ids,
                                                                         _node_indices)

    if n_mortars > 0
        init_mortars!(mortars, mesh)
    end

    return mortars
end
```

2025-04-01 22:24 UTC, andrewwinters5000 commented
I am not sure why the new `resize!` function is marked as uncovered by codecov. It definitely fires from the test case contained in the new test `examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry.jl`.

2025-04-03 07:28 UTC, patrickersing requested changes
Thanks for adding this! Having support for AMR is a really nice addition to TrixiSW.
Overall this looks already pretty good, besides the mentioned issues with AMR at wet/dry transitions. I had a few questions on the implementation and added some smaller suggestions.

It is weird that these lines are marked as uncovered, but we have experienced such a problem before in https://github.com/trixi-framework/TrixiShallowWater.jl/pull/38. Could it also be that the `resize!` function is not called directly in the first time step?

It would also be good if someone who is more familiar with the p4est / mortar implementations could have a second look at the respective parts.

2025-04-03 07:28 UTC, patrickersing commented on test/runtests.jl
Since this PR introduces many new interactions with `Trixi.jl` it would be good to also include one AMR example in the `upstream` tests.

2025-04-04 12:08 UTC, ranocha requested changes
Thanks! I mostly looked at this from a Julia perspective and less from an algorithmic perspective. I am curious to see where the remaining issues come from.

2025-04-04 12:08 UTC, ranocha commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            u_buffer[2:4, i] = u[2:4, i_large, j_large, element]
This will allocate

```suggestion
            for v in 2:4
                u_buffer[v, i] = u[v, i_large, j_large, element]
            end
```

2025-04-04 12:08 UTC, ranocha commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            tol = 1e-4
```suggestion
            tol = convert(eltype(cache.mortars.u), 1.0e-4)
```

2025-04-04 12:08 UTC, ranocha commented on src/solvers/dgsem_p4est/dg_2d.jl
> +                cache.mortars.u[side, 2, child, i, mortar] = h * (2.0 * h *
```suggestion
                cache.mortars.u[side, 2, child, i, mortar] = h * (2 * h *
```

2025-04-04 12:08 UTC, ranocha commented on src/solvers/dgsem_p4est/dg_2d.jl
> +                cache.mortars.u[side, 3, child, i, mortar] = h * (2.0 * h *
```suggestion
                cache.mortars.u[side, 3, child, i, mortar] = h * (2 * h *
```

2025-04-04 12:08 UTC, ranocha commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            cache.mortars.u_parent[2, i, mortar] = h * (2.0 * h *
```suggestion
            cache.mortars.u_parent[2, i, mortar] = h * (2 * h *
```

2025-04-04 12:08 UTC, ranocha commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            cache.mortars.u_parent[3, i, mortar] = h * (2.0 * h *
```suggestion
            cache.mortars.u_parent[3, i, mortar] = h * (2 * h *
```

2025-04-04 12:08 UTC, ranocha commented on src/solvers/dgsem_p4est/dg_2d.jl
> +        flux_plus_noncons = flux + 0.5 * noncons
```suggestion
        flux_plus_noncons = flux + 0.5f0 * noncons
```

2025-04-22 19:44 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry.jl
> +# Further investigation is needed to identify exactly why each aspect of this strange behavior occurs
I need to double check, but I believe the loss of conservation is also present without AMR. These comments were mainly running notes to myself and could be removed here and added to the issue #77 instead to keep everything centralized.

2025-04-22 19:46 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry.jl
> +                flux_nonconservative_chen_noelle)
No, using Audusse et al. doesn't really change the behavior. The Audusse et al. reconstruction works and we get wet/dry well-balancedness if I change the reconstruction to be
```julia
    # Compute the reconstructed water heights
    h_ll_star = max(5*eps(), h_ll + b_ll - max(b_ll, b_rr))
    h_rr_star = max(5*eps(), h_rr + b_rr - max(b_ll, b_rr))
```
but with the AMR we have the same conservation issues and it ends up at ≈ 1e-5

2025-04-22 19:51 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry.jl
> +    return SVector(h, h * v1, h * v2, b)
Good catch! I was experimenting with this alternative way of setting up the initial condition to see if it made any difference. We should change it back for consistency.

2025-04-22 19:59 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/containers.jl
> +
A docstring makes the reference links nicer and the Experimental warning more visible, but I do not have a strong opinion either way.

2025-04-22 20:02 UTC, andrewwinters5000 commented on src/solvers/indicators_1d.jl
> +            alpha[element] = one(alpha_element)
I thought that this would make sure that `alpha[element]` has the same type as `alpha_element`. If that is not the case I can change it back.

2025-04-22 20:03 UTC, andrewwinters5000 commented on src/solvers/indicators_2d.jl
> +            alpha[element] = one(alpha_element)
Same as above

2025-04-22 20:16 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +# and directly placed in the nonconservative flux
Yeah, one probably doesn't need the `u_parent` to get well-balancedness as the back projection should already contain the pressure contributions that balance. The only thing that should need extended is how one "grabs" the variables during the projection onto the mortars. Right now it is hard coded the index `1` is the water height, indices `2` and `3` are the momenta, index `4` is the bottom. However, with multilayer we would need to take a strategy similar to how the limiter grabs the water heights and momenta.

2025-04-22 20:19 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +               2 * (equations.threshold_limiter + eps())
I know that if one only uses `equations.threshold_limiter` then we lose well-balancedness for wet/dry. I need to test again what happens if we can just use `2 * equations.threshold_limiter`. I remember this being very sensitive.

2025-04-22 20:21 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            tol = 1e-4
Now that we have the additional `threshold_desingularization` available I should be able to grab this tolerance directly. Although this requires some testing.

2025-04-22 20:21 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            end
True, although I was trying to avoid such clipping because (I think) it might contribute to the conservation loss.

2025-04-22 20:22 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +    end
I thought it would be, but in my testing if I did not again perform this step on the mortars things starting crashing again.

2025-04-22 20:42 UTC, andrewwinters5000 commented on src/solvers/indicators_1d.jl
> +            alpha[element] = one(alpha_element)
This is also how Trixi does it, https://github.com/trixi-framework/Trixi.jl/blob/main/src/solvers/dgsem_tree/indicators_1d.jl#L85-L88, so I assumed it was the "proper" way.

2025-04-22 20:53 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation.jl
Done in 8b0639f40e52293935fade6a7ee8012aeac88fb4

2025-04-22 20:53 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry.jl
Done in 8b0639f40e52293935fade6a7ee8012aeac88fb4

2025-04-22 20:53 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_well_balanced.jl
Done in 8b0639f40e52293935fade6a7ee8012aeac88fb4

2025-04-22 20:54 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_well_balanced_wet_dry.jl
Done in 8b0639f40e52293935fade6a7ee8012aeac88fb4

2025-04-22 20:55 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation.jl
> +end
Done in 9dd14a4150b80b5406c92d45aba9203e03ba8b89

2025-04-22 20:55 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry.jl
> +end
Done in 9dd14a4150b80b5406c92d45aba9203e03ba8b89

2025-04-22 21:38 UTC, andrewwinters5000 commented on test/runtests.jl
An upstream test was added in 91281f516d87c68cbcf201d7d948ec8b0e34b2c9

2025-04-23 08:10 UTC, patrickersing commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            end
Right, this can definitely contribute to conservation loss so if we could get rid of it that would be good.
Though the suggestion doesn't change any of the current behavior. Right now we first desingularize and then if `h<threshold` we overwrite the computed velocity value with `v=0`. The idea is that with this change we would only apply the desingularization when it is actually required.

2025-04-23 08:17 UTC, patrickersing commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry.jl
> +# Further investigation is needed to identify exactly why each aspect of this strange behavior occurs
Since the elixir might show some unexpected behavior, I like to have the comment in there to make users aware of the present issues. 
I was just curios if the issues get introduced by AMR or if they were already present on the nonconforming mesh.

2025-04-23 08:29 UTC, patrickersing commented on src/solvers/dgsem_p4est/dg_2d.jl
> +    end
I noticed that for the `ShallowWaterEquationsWetDry2D` we added the velocity desingularization just recently https://github.com/trixi-framework/TrixiShallowWater.jl/pull/83. Do you recall if you tested this before or after merging that PR? This could possibly be an explanation for the differences.

2025-04-23 09:09 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +    end
It was definitely tested before #83 was merged. So, I need to revisit the desingularization strategy on the mortars. I think that one would only need to perform it on the projected parent solution onto the children.

2025-04-23 09:11 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            end
Ah, sorry. I got confused with what you wanted to do. Yes, that seems reasonable to not "overwrite" values.

2025-04-25 21:06 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +               2 * (equations.threshold_limiter + eps())
I can confirm that using `equations.threshold_limiter` loses WB error up to `1e-6` on the wet/dry test. However, using `2 * equations.threshold_limiter` gives `1e-16`. So removing the `eps()` seems reasonable.

2025-04-25 21:12 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +               2 * (equations.threshold_limiter + eps())
Nevermind, when running the WB with wet/dry longer (beyond final time 10) we lose WB without the extra `eps()`

2025-04-25 21:20 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +               2 * (equations.threshold_limiter + eps())
In the nonconforming wet/dry case adding `eps()` in this check maintains WB while removing the `eps()` causes blow up. So we should keep this `eps()` shift (for now)

2025-04-28 19:49 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +               2 * (equations.threshold_limiter + eps())
Nevermind, this was a CFL issue. We should be able to remove the additional `eps()`

2025-04-28 19:50 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +    end
Now that I experimented with this more, we do not need to do this safety desingularization of the `u_parent` solution. The results are the same if I remove this code.

2025-04-28 19:52 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_perturbation_wet_dry.jl
> +# Further investigation is needed to identify exactly why each aspect of this strange behavior occurs
I updated the text here with some new information. It is still very sensitive especially if I take the desginularization threshold above `5e-5`. Any values of the desingularization threshold and CFL number I have tried up to now loses conservation as before.

2025-04-29 05:14 UTC, andrewwinters5000 commented on src/solvers/dgsem_p4est/dg_2d.jl
> +            tol = 1e-4
Now I pass this tolerance into the equations constructor as `threshold_desingularization`, so the type conversion should be done under the hood.

2025-04-29 08:54 UTC, patrickersing requested changes
From my end this looks almost ready to merge. I just have a question and one comment that needs to be changed.

2025-04-29 08:59 UTC, patrickersing commented
> I wonder if all the coveralls "noise" in the CI means we should update the reporting strategy as mentioned [here](https://github.com/trixi-framework/TrixiBottomTopography.jl/pull/55#discussion_r2060242495)

Since the coverage issue has been solved by setting a higher `maxiters` in the coverage run, I would say we can move the discussion about this to a separate issue.

2025-04-29 10:21 UTC, ranocha reviewed
Do you want me to review the PR again? If so, please let me know (and tell me whether there is anything in particular you where you would like to have feedback). Otherwise, I am fine merging this PR when the remaining comments of Patrick are resolved.

2025-04-29 10:21 UTC, ranocha commented on docs/make.jl
> +open(joinpath(@__DIR__, "src", "changelog.md"), "w") do io
Maybe add this generated file to `.gitignore`?

2025-04-29 11:13 UTC, andrewwinters5000 commented on examples/p4est_2d_dgsem/elixir_shallowwater_well_balanced_nonconforming.jl
> +            save_everystep = false, callback = callbacks, maxiters = 2e5);
This is needed to run to the final time of `100.0` in the elixir. It takes about 130,000 time steps.

2025-04-29 12:27 UTC, ranocha approved these changes

2025-04-29 14:03 UTC, patrickersing approved these changes

2025-04-29 17:37 UTC, andrewwinters5000 commented
Thanks a lot @ranocha and @patrickersing for your help getting this experimental feature over the finish line!

2025-04-29 17:38 UTC, merged